# IntelliJ Platform
pluginGroup = com.github.azmiao.gitmoji
pluginName = GitEmojiLint
pluginVersion = 1.0.0
pluginSinceBuild = 242
pluginUntilBuild =

# IDE version for development
platformType = IC
platformVersion = 2024.2

# Java
javaVersion = 21

# JDK 21 安装路径
org.gradle.java.home = C:\\AZMIAO\\04-Deps\\Java\\jdk-21.0.10
